/**
 * Static fallback data - mirrors current hardcoded page content.
 * Used when the backend is unavailable during `astro build`.
 */

import type { SolutionTrackDetail, ContactProfile } from './api';

export const CYBERSECURITY_FALLBACK: SolutionTrackDetail = {
  slug: 'cybersecurity',
  title: 'Cybersecurity',
  short_summary: 'Risk reduction, testing, privacy, and strategic leadership.',
  hero_title: 'Cybersecurity Services',
  hero_body: 'Cyberfyx brings robust capabilities in delivering scalable, end-to-end IT security services tailored for diverse industry needs. Our team comprises certified security professionals with hands-on experience across cloud, on-premise, and hybrid infrastructures. With proven execution in vulnerability management, compliance (ISO 27001, ISO 27701, ISO 22301 etc), endpoint protection, and red team operations, we serve clients ranging from startups to large enterprises. Backed by strong GRC expertise and strategic advisory support, Cyberfyx ensures organizations are both resilient and audit-ready. Our adaptable staffing and 24/7 support models ensure rapid response and long-term security program success.',
  cta_label: 'Get in touch',
  cta_target: '/contact',
  display_order: 1,
  meta_title: 'Cybersecurity Services | Cyberfyx',
  meta_description: 'Risk reduction, testing, privacy, and strategic leadership.',
  offerings: [
    {
      slug: 'vapt',
      title: 'VAPT',
      kicker: 'Vulnerability Assessment & Penetration Testing',
      description: 'Comprehensive vulnerability assessment and penetration testing across web, mobile, and network infrastructure.',
      display_order: 1,
      taxonomy_terms: [],
    },
    {
      slug: 'grc-maintenance',
      title: 'GRC Maintenance',
      kicker: 'Governance, Risk & Compliance',
      description: 'Ongoing governance, risk, and compliance program management and maintenance.',
      display_order: 2,
      taxonomy_terms: [],
    },
    {
      slug: 'pci-dss',
      title: 'PCI DSS Readiness',
      kicker: 'Payment Card Industry',
      description: 'Gap assessments and readiness support for PCI DSS certification.',
      display_order: 3,
      taxonomy_terms: [],
    },
    {
      slug: 'vciso-dpo',
      title: 'vCiso & DPO',
      kicker: 'Virtual CISO & Data Protection Officer',
      description: 'Strategic security leadership, roadmap planning, and data protection advisory.',
      display_order: 4,
      taxonomy_terms: [],
    },
    {
      slug: 'gdpr-ccpa-dpdpa',
      title: 'GDPR - CCPA - DPDPA',
      kicker: 'Privacy & Data Protection Compliance',
      description: 'Privacy compliance programs for global and Indian data protection regulations.',
      display_order: 5,
      taxonomy_terms: [],
    },
    {
      slug: 'red-team',
      title: 'Red Team Assignment',
      kicker: 'Adversarial Simulation',
      description: 'Simulated adversarial attacks to test and strengthen security defenses.',
      display_order: 6,
      taxonomy_terms: [],
    },
    {
      slug: 'soc',
      title: 'Security Operation Center',
      kicker: 'SOC as a Service',
      description: '24/7 monitoring and threat response through managed SOC services.',
      display_order: 7,
      taxonomy_terms: [],
    },
    {
      slug: 'hipaa',
      title: 'HIPAA',
      kicker: 'Healthcare Information Privacy',
      description: 'HIPAA compliance advisory and audit support for healthcare organizations.',
      display_order: 8,
      taxonomy_terms: [],
    },
    {
      slug: 'soc2-type2',
      title: 'SOC 2 Type 2',
      kicker: 'Service Organization Controls',
      description: 'SOC 2 readiness assessment and evidence collection for SaaS providers.',
      display_order: 9,
      taxonomy_terms: [],
    },
    {
      slug: 'cmmi',
      title: 'CMMI',
      kicker: 'Capability Maturity Model Integration',
      description: 'Process improvement and capability maturity assessment.',
      display_order: 10,
      taxonomy_terms: [],
    },
  ],
  endpoint_rows: [],
};

export const IT_SECURITY_FALLBACK: SolutionTrackDetail = {
  slug: 'it-security',
  title: 'IT Security',
  short_summary: 'Framework implementation, internal audits, continuity, and cloud governance.',
  hero_title: 'IT Security Solutions',
  hero_body: 'Cyberfyx brings robust capabilities in delivering scalable, end-to-end IT security services tailored for diverse industry needs. Our team comprises certified security professionals with hands-on experience across cloud, on-premise, and hybrid infrastructures. With proven execution in vulnerability management, compliance (ISO 27001, ISO 27701, ISO 22301 etc), endpoint protection, and red team operations, we serve clients ranging from startups to large enterprises. Backed by strong GRC expertise and strategic advisory support, Cyberfyx ensures organizations are both resilient and audit-ready. Our adaptable staffing and 24/7 support models ensure rapid response and long-term security program success.',
  cta_label: 'Get in touch',
  cta_target: '/contact',
  display_order: 2,
  meta_title: 'IT Security Solutions | Cyberfyx',
  meta_description: 'Framework implementation, internal audits, continuity, and cloud governance.',
  offerings: [
    {
      slug: 'iso-27001',
      title: 'ISO 27001:2022',
      kicker: 'Information Security Management System',
      description: 'Establishes a risk-based security framework to protect information assets. Cyberfyx enables full lifecycle support from policy creation to audit preparation.',
      display_order: 1,
      taxonomy_terms: [],
    },
    {
      slug: 'iso-27701',
      title: 'ISO 27701:2019',
      kicker: 'Privacy Information Management System',
      description: 'Extends ISO 27001 for data privacy governance aligned with global laws like GDPR. We help organizations manage personal data processing with accountability and transparency.',
      display_order: 2,
      taxonomy_terms: [],
    },
    {
      slug: 'iso-22301',
      title: 'ISO 22301:2019',
      kicker: 'Business Continuity Management System',
      description: 'Ensures preparedness and resilience against business disruptions and disasters. Cyberfyx supports BIA, continuity planning, and recovery drills for certification.',
      display_order: 3,
      taxonomy_terms: [],
    },
    {
      slug: 'iso-20000',
      title: 'ISO 20000-1:2018',
      kicker: 'IT Service Management System',
      description: 'Sets global standards for delivering managed IT services effectively and efficiently. Our experts implement ITSM processes aligned with business performance goals.',
      display_order: 4,
      taxonomy_terms: [],
    },
    {
      slug: 'iso-27017-27018',
      title: 'ISO 27017 & 27018',
      kicker: 'Cloud Security & Privacy Controls',
      description: 'Provides cloud-specific guidance for security and personal data protection. We help cloud service providers and customers secure and govern cloud environments.',
      display_order: 5,
      taxonomy_terms: [],
    },
    {
      slug: 'iso-42001',
      title: 'ISO 42001',
      kicker: 'AI Management System',
      description: 'A new framework for responsible, secure, and transparent use of Artificial Intelligence. Cyberfyx assists in aligning AI systems with ethical, legal, and risk-based standards.',
      display_order: 6,
      taxonomy_terms: [],
    },
    {
      slug: 'csa-star',
      title: 'CSA STAR',
      kicker: 'Cloud Security Alliance Certification',
      description: 'Recognized cloud security certification combining ISO 27001 with CSA controls. We guide SaaS, PaaS, and IaaS providers through gap analysis and self-assessments.',
      display_order: 7,
      taxonomy_terms: [],
    },
    {
      slug: 'tisax',
      title: 'TISAX',
      kicker: 'Trusted Information Security Assessment Exchange',
      description: 'Required by the automotive industry for secure handling of sensitive data. Cyberfyx helps suppliers prepare for TISAX through risk assessments and audit support.',
      display_order: 8,
      taxonomy_terms: [],
    },
    {
      slug: 'internal-audits',
      title: 'Internal Audits & Assessments',
      kicker: 'Ongoing Compliance',
      description: 'Regular reviews to ensure ongoing compliance, effectiveness, and readiness.',
      display_order: 9,
      taxonomy_terms: [],
    },
  ],
  endpoint_rows: [],
};

export const ENDPOINT_FALLBACK: SolutionTrackDetail = {
  slug: 'endpoint-operations',
  title: 'Endpoint Operations',
  short_summary: 'Visibility, automation, monitoring, and lifecycle control.',
  hero_title: 'Smart Endpoint Management',
  hero_body: 'CYBERFYX is a trusted authorized solution partner of IPM+ Endpoint Management Solutions, empowering enterprises with intelligent and secure device management. We deliver seamless deployment, optimization, and compliance-driven control across all endpoints using IPM+\'s powerful automation and analytics. Together, we help organizations enhance IT efficiency, reduce risks, and ensure enterprise-wide visibility and control.',
  cta_label: 'Get in touch',
  cta_target: '/contact',
  display_order: 3,
  meta_title: 'Smart Endpoint Management | Cyberfyx',
  meta_description: 'Visibility, automation, monitoring, and lifecycle control.',
  offerings: [],
  endpoint_rows: [
    {
      product_name: 'IPM+ Unified Endpoint Management',
      solution_name: 'Endpoint Management Solutions',
      service_name: 'Green Private Cloud (VPC)',
      display_order: 1,
    },
    {
      product_name: 'IPM+ Unified Monitoring Solutions',
      solution_name: 'Industry 4.0 Solutions',
      service_name: 'Enterprise Architecture Consulting',
      display_order: 2,
    },
    {
      product_name: 'IPM+ SmartDC',
      solution_name: 'Smart Buildings IoT Solutions',
      service_name: 'Industry 4.0 Digital Transformation',
      display_order: 3,
    },
    {
      product_name: 'IPM+ SIEM',
      solution_name: 'Datacenter Management Solutions',
      service_name: 'Efficient Data Centre Design',
      display_order: 4,
    },
    {
      product_name: 'IPM+ Cloud',
      solution_name: 'NOC Solutions',
      service_name: 'DR Service',
      display_order: 5,
    },
    {
      product_name: 'PowerMind AI',
      solution_name: 'Backup Solutions',
      service_name: '',
      display_order: 6,
    },
    {
      product_name: 'IPM+ Backup Pro',
      solution_name: 'Resource Monitoring Solutions',
      service_name: '',
      display_order: 7,
    },
    {
      product_name: 'IPM+ Powerwise Pro',
      solution_name: '',
      service_name: '',
      display_order: 8,
    },
  ],
};

export const CORE_INDUSTRY_FALLBACK: SolutionTrackDetail = {
  slug: 'core-industry-services',
  title: 'Core Industry Services',
  short_summary: 'Management systems, sector audits, and industrial assurance.',
  hero_title: 'Core Industry Services',
  hero_body: 'Cyberfyx provides end-to-end support, from gap assessments, documentation, training, and internal audits to certification liaison and post-certification maintenance. We ensure that management systems are not just compliant, but also integrated, efficient, and aligned with business performance objectives.',
  cta_label: 'Get in touch',
  cta_target: '/contact',
  display_order: 4,
  meta_title: 'Core Industry Services | Cyberfyx',
  meta_description: 'Management systems, sector audits, and industrial assurance.',
  offerings: [
    {
      slug: 'iso-9001',
      title: 'ISO 9001 – Quality Management System',
      kicker: 'Quality Management',
      description: 'We help organizations establish robust QMS frameworks for consistent product and service delivery. Cyberfyx supports policy development, process mapping, internal audits, and certification readiness.',
      display_order: 1,
      taxonomy_terms: [],
    },
    {
      slug: 'iso-14001',
      title: 'ISO 14001 – Environmental Management System',
      kicker: 'Environmental Management',
      description: 'Cyberfyx enables companies to implement eco-conscious operational controls, perform environmental impact assessments, and maintain regulatory compliance with sustainability goals.',
      display_order: 2,
      taxonomy_terms: [],
    },
    {
      slug: 'iso-45001',
      title: 'ISO 45001 – Occupational Health & Safety Management System',
      kicker: 'Health & Safety',
      description: 'We assist in creating safe work environments by implementing hazard identification, risk mitigation, and safety culture practices aligned with ISO 45001 requirements.',
      display_order: 3,
      taxonomy_terms: [],
    },
    {
      slug: 'as9100',
      title: 'AS9100 – Aerospace Quality Management',
      kicker: 'Aerospace Quality',
      description: 'Tailored for the aerospace sector, Cyberfyx supports the implementation of AS9100 standards with a focus on product safety, risk management, and regulatory alignment.',
      display_order: 4,
      taxonomy_terms: [],
    },
    {
      slug: 'iatf-16949',
      title: 'IATF 16949 – Automotive Quality Management System',
      kicker: 'Automotive Quality',
      description: 'For the automotive supply chain, Cyberfyx delivers gap assessments, process optimization, and audit support to help organizations meet the quality expectations of OEMs and Tier-1 suppliers.',
      display_order: 5,
      taxonomy_terms: [],
    },
    {
      slug: 'fire-safety-audit',
      title: 'Fire Safety Audit',
      kicker: 'Fire & Safety Compliance',
      description: 'We assess fire protection systems, evacuation protocols, and risk controls as per NBC and local fire regulations. Cyberfyx ensures your premises meet safety compliance and insurance requirements.',
      display_order: 6,
      taxonomy_terms: [],
    },
    {
      slug: 'fsc-audit',
      title: 'Forest Stewardship Council (FSC) Audit',
      kicker: 'Sustainable Forestry',
      description: 'Ensures responsible sourcing and sustainable forest management practices in line with FSC Chain of Custody (CoC) standards. Cyberfyx supports FSC audit readiness, documentation, traceability, and supplier compliance.',
      display_order: 7,
      taxonomy_terms: [],
    },
    {
      slug: 'sedex-audit',
      title: 'SEDEX Audit (SMETA)',
      kicker: 'Social Compliance',
      description: 'Social compliance audit based on labor rights, health & safety, environment, and business ethics. Cyberfyx helps you prepare for SMETA 2/4-pillar audits and improve your supplier credibility.',
      display_order: 8,
      taxonomy_terms: [],
    },
    {
      slug: 'awareness-training',
      title: 'Awareness & Internal Auditor Training',
      kicker: 'Training & Capability Building',
      description: 'We deliver structured training for ISO standards, compliance frameworks, and audit skills. Our programs equip teams to understand requirements and independently conduct internal audits.',
      display_order: 9,
      taxonomy_terms: [],
    },
  ],
  endpoint_rows: [],
};

export const TRAINING_FALLBACK: SolutionTrackDetail = {
  slug: 'training',
  title: 'Training',
  short_summary: 'Capability building for security, privacy, governance, and recovery teams.',
  hero_title: 'Cybersecurity Training',
  hero_body: 'Empower your workforce with the knowledge and skills needed to recognize and prevent cyber attacks before they impact your business.',
  cta_label: 'Get in touch',
  cta_target: '/contact',
  display_order: 5,
  meta_title: 'Cybersecurity Training | Cyberfyx',
  meta_description: 'Capability building for security, privacy, governance, and recovery teams.',
  offerings: [
    {
      slug: 'iso-27001-awareness',
      title: 'ISO/IEC 27001:2022 Awareness & Internal Audit',
      kicker: 'Intermediate · 2 Days · For: ISMS implementers, audit teams',
      description: 'ISO 27001:2022 awareness and internal auditor training for ISMS implementers and audit teams.',
      display_order: 1,
      taxonomy_terms: [],
    },
    {
      slug: 'gdpr-workshop',
      title: 'GDPR Compliance Workshop',
      kicker: 'Intermediate · 1 Day · For: DPOs, IT, legal, marketing teams',
      description: 'Practical GDPR compliance training for DPOs, IT staff, legal, and marketing teams.',
      display_order: 2,
      taxonomy_terms: [],
    },
    {
      slug: 'hipaa-training',
      title: 'HIPAA Security & Privacy',
      kicker: 'Intermediate · 1 Day · For: Healthcare IT teams',
      description: 'HIPAA security and privacy training for healthcare IT teams and compliance staff.',
      display_order: 3,
      taxonomy_terms: [],
    },
    {
      slug: 'pci-dss-training',
      title: 'PCI DSS Readiness Training',
      kicker: 'Intermediate · 1 Day · For: Payment service teams',
      description: 'PCI DSS readiness training tailored for payment service and e-commerce teams.',
      display_order: 4,
      taxonomy_terms: [],
    },
    {
      slug: 'soc2-foundation',
      title: 'SOC 2 & SOC 1 Compliance Foundation',
      kicker: 'Intermediate · 1 Day · For: SaaS businesses, audit teams',
      description: 'SOC 2 and SOC 1 compliance foundation training for SaaS businesses and audit teams.',
      display_order: 5,
      taxonomy_terms: [],
    },
    {
      slug: 'nist-csf',
      title: 'NIST CSF & Risk Management Framework',
      kicker: 'Advanced · 2 Days · For: Government, finance, critical infra',
      description: 'Advanced NIST Cybersecurity Framework and Risk Management Framework training for government, finance, and critical infrastructure teams.',
      display_order: 6,
      taxonomy_terms: [],
    },
    {
      slug: 'it-governance',
      title: 'IT Governance (COBIT & ITIL v4) Awareness',
      kicker: 'Intermediate · 1 Day · For: IT managers, auditors',
      description: 'IT governance awareness covering COBIT and ITIL v4 frameworks for IT managers and auditors.',
      display_order: 7,
      taxonomy_terms: [],
    },
    {
      slug: 'bcdr-training',
      title: 'Business Continuity & Disaster Recovery',
      kicker: 'Intermediate · 1 Day · For: Risk managers, compliance leads',
      description: 'Business continuity and disaster recovery training for risk managers and compliance leads.',
      display_order: 8,
      taxonomy_terms: [],
    },
  ],
  endpoint_rows: [],
};

export const CONTACT_PROFILE_FALLBACK: ContactProfile = {
  profile_key: 'primary',
  sales_email: 'sales@cyberfyx.net',
  hr_email: 'hr@cyberfyx.net',
  primary_phone: '+91 9663410308',
  headquarters_name: 'Cyberfyx',
  headquarters_address: 'Janardhana Towers, Ashok Nagar, Bengaluru 560025',
  map_url: 'https://www.google.com/maps/search/?api=1&query=Janardhana%20Towers%2C%20Ashok%20Nagar%2C%20Bengaluru%20560025',
  office_regions: [
    { slug: 'india', label: 'India', display_order: 1 },
    { slug: 'singapore', label: 'Singapore', display_order: 2 },
    { slug: 'philippines', label: 'Philippines', display_order: 3 },
    { slug: 'dubai', label: 'Dubai', display_order: 4 },
  ],
  interest_options: [
    {
      slug: 'cybersecurity-services',
      label: 'Cybersecurity',
      route_target: '/services/cybersecurity',
      display_order: 1,
    },
    {
      slug: 'it-security-and-continuity',
      label: 'IT Security',
      route_target: '/services/it-security',
      display_order: 2,
    },
    {
      slug: 'endpoint-management-services',
      label: 'Endpoint Management',
      route_target: '/services/endpoint-management',
      display_order: 3,
    },
    {
      slug: 'core-industry-services',
      label: 'Core Industry Services',
      route_target: '/services/core-industry',
      display_order: 4,
    },
    {
      slug: 'training',
      label: 'Training',
      route_target: '/services/training',
      display_order: 5,
    },
    {
      slug: 'general-inquiry',
      label: 'General Inquiry',
      route_target: '/contact',
      display_order: 6,
    },
  ],
};
